### ISSUE TITLE
DataSourceDatabaseModule fails if I inject the injector

### ISSUE THREAD

**Issue by lhahne** [EvidentSolutions/dalesbred#1]
I am trying to use dalesbred with quartz and guice. What I am doing is basically injecting the injector to instantiate the jobs as described in http://blog.timmattison.com/archives/2014/08/05/using-guice-dependency-injection-with-quartz-schedulding/. My other modules work fine but dalesbred gives the following error.

```
1) Unable to create binding for fi.evident.dalesbred.Database. It was already configured on one or more child injectors or private modules
    bound at fi.evident.dalesbred.support.guice.DataSourceDatabaseModule.configure(DataSourceDatabaseModule.java:62)
  If it was in a PrivateModule, did you forget to expose the binding?
  while locating fi.evident.dalesbred.Database
    for parameter 0 at jobs.PollerJob.<init>(PollerJob.java:20)
  while locating jobs.PollerJob
```

**Comment by komu** [comment]
Without seeing the configuration it's really hard for me to guess what's wrong. Have you bound the database with a different key? If you call `Injector.getInstance(Database.class)` in some other context does it work? If you just `@Inject Database` normally elsewhere, does it work?

**Comment by lhahne** [comment]
I think there's too much configuration to copy-paste it but essentially I set up hikari like

```
bind(DataSource.class).toProvider(HikariDataSourceProvider.class).in(Scopes.SINGLETON);
```

in my own DataSourceModule and the actual injector is created using governator like

```
    Injector injector = LifecycleInjector.builder()
            .withAdditionalModuleClasses(DataSourceModule.class, DataSourceDatabaseModule.class)
            .withBootstrapModule((binder) -> {
                binder.bindConfigurationProvider().toInstance(configurationProvider);
            })
            .build()
            .createInjector();
```

If I get the injector manually in my job, then everything works ok, but if I inject the injector, I'll get the error that I posted above. Hikari seems to work ok even with the injected injector.

**Comment by lhahne** [comment]
So this works

```
public class PollerJob implements Job {

    private Database db;

    public PollerJob() {
        db = InjectorHolder.getInjector().getInstance(Database.class);
    }

    public void execute(JobExecutionContext context) throws JobExecutionException {
        log.info("it works");
    }

}
```

This doesn't

```
public class PollerJob implements Job {

    private Database db;

    @Inject
    public PollerJob(Database db) {
      this.db = db;
    }

    public void execute(JobExecutionContext context) throws JobExecutionException {
        log.info("crash and burn");
    }

}
```

**Comment by komu** [comment]
Since both [DataSourceDatabaseModule](https://github.com/EvidentSolutions/dalesbred/blob/master/dalesbred/src/main/java/fi/evident/dalesbred/support/guice/DataSourceDatabaseModule.java) and [DatabaseProvider](https://github.com/EvidentSolutions/dalesbred/blob/master/dalesbred/src/main/java/fi/evident/dalesbred/support/guice/DatabaseProvider.java) are very straightforward and don't contain anything interesting it's a bit hard to believe that the problem is there instead of your configuration.

What version of Dalesbred are you using? What makes you think that Dalesbred is the cause of the problem? Based on the error messages it seems that you have multiple definitions for the binding. Do you understand what kind of configuration is built by governator? Governator makes it quite easy to fallback to just cargo-culting the configuration.

Anyway, if I'll get reproducible example project, I can look into the problem, but otherwise it's really hard for me to justify spending time on this as it looks to me to be a Guice configuration problem rather than a bug in Dalesbred.

**Comment by komu** [comment]
Without further input I'll assume this was invalid. If you can provide a reproducible test case or other info, we can reopen this.
