### ISSUE TITLE
Support transactions managed by JTA

### ISSUE THREAD

**Issue by dansofinskiy** [EvidentSolutions/dalesbred#17]
I have configuration with MySQL database and WildFly application server, and I try to work with dalesberd as simple jdbc wrapper.
I am trying to lookup datasource from jndi, and work with some data like this:

``` java
Database db = Database.forJndiDataSource("java:/my/data/source");
            db.setAllowImplicitTransactions(false);
            db.withTransaction(tx -> new TransactionCallback<Void>() {

                public Void execute(TransactionContext tx) throws SQLException {
                    long entity = db.findUniqueLong("SELECT COUNT(*) FROM example");
                    if (0 == entity) {
                        db.update("INSERT INTO example(/*...*/) VALUES(/*...*/)");
                    }
                    return null;
                }
            });
```

, and I have 

```
java.sql.SQLException: You cannot set autocommit during a managed transaction!
    at org.jboss.jca.adapters.jdbc.BaseWrapperManagedConnection.setJdbcAutoCommit(BaseWrapperManagedConnection.java:968)
    at org.jboss.jca.adapters.jdbc.WrappedConnection.setAutoCommit(WrappedConnection.java:716)
    at org.dalesbred.transaction.DefaultTransactionManager.openConnection(DefaultTransactionManager.java:95)
```

because MySQL set autocommit on by default (And I can't disable it).

Same exception, if I don't use setAllowImplicitTransaction() and withTransaction().
What can I do in this situation?

**Comment by komu** [comment]
Unfortunately this is currently not supported automatically. I do agree that integrating with JTA should probably be something that Dalesbred should support out of the box, so I'm scheduling this for next release. Dalesbred should try to find JTA services from JNDI and use those automatically just by saying something like: `DataBase.forJndiDataSourceAndJTA("java:/my/data/source")`

For now, you have at least two options:
1. You can implement Dalesbred's [TransactionManager](http://dalesbred.org/docs/api/org/dalesbred/transaction/TransactionManager.html) yourself so that it delegates to JTA and then create `Database` with your own transaction manager: `new Database(myTransactionManager)`. It's not nice to have to do this, but at least it's possible.
   
   If you do this, consider submitting a pull request so that the TransactionManager can be included in Dalesbred as well. (Although Dalesbred's implementation would have to work with any container whereas you could cut corners by implementing it only for JBoss.)
2. You can take advantage of the fact that Spring already implements this with its [JtaTransactionManager](http://docs.spring.io/spring-framework/docs/4.2.x/javadoc-api/org/springframework/transaction/jta/JtaTransactionManager.html) and Dalesbred supports delegating to Spring with its own [SpringTransactionManager](http://dalesbred.org/docs/api/org/dalesbred/integration/spring/SpringTransactionManager.html). So if you can depend on `spring-tx`, you could say something like this:
   
   ``` java
   DataSource ds = JndiUtils.lookupJndiDataSource("java:/my/data/source");
   JtaTransactionManager tm = new JtaTransactionManager();
   // ...possible tm-configuration here...
   tm.afterPropertiesSet();
   Database db = new Database(new SpringTransactionManager(ds, tm));
   ```
   
   Of course if you're using Spring for other purposes as well, then you can wire `JtaTransactionManager` normally using Spring, but if you need Spring just for this, you can ignore rest of the framework.

If you wish to pursue the first route and implement your own TransactionManager without using Spring, I suggest taking a look at implementation of Spring's JtaTransactionManager because it should contain everything you need.

Hope this helps. Ask if anything is unclear.

I will schedule this for 1.1 because it really should be possible to integrate with JTA without writing your own code or using Spring.

**Comment by komu** [comment]
And a sidenote: this won't fix your problem, but you can simplify the last statement of your original code to:

``` java
db.withVoidTransaction(tx -> {
    long entity = db.findUniqueLong("SELECT COUNT(*) FROM example");
    if (0 == entity) {
        db.update("INSERT INTO example(/*...*/) VALUES(/*...*/)");
    }
});
```

**Comment by dansofinskiy** [comment]
Thank you for answer.
But in our cases sometimes no need of JTA and this example are one of this.
So, I'll be waiting for next release.

**Comment by jlogar** [comment]
I played around with dalesbred and didn't want to jump through all the hoops with CDI, JNDI and whatnots. I came up with this poor mans transaction manager:

``` java
@Stateless
public class DirectDb {
    @Resource
    DataSource dataSource;
    @Resource
    private EJBContext context;

    public <T> List<T> findAll(@SQL String sql, Class<T> clazz) {
        Database db = new Database(new JtaTransactionManager(dataSource, context));
        db.setAllowImplicitTransactions(false);
        return db.findAll(clazz, sql);
    }

    public static class JtaTransactionManager implements TransactionManager {
        private final DataSource ds;
        private final EJBContext context;

        public JtaTransactionManager(DataSource ds, EJBContext context) {
            this.ds = ds;
            this.context = context;
        }

        @Override
        public <T> T withTransaction(TransactionSettings transactionSettings, TransactionCallback<T> transactionCallback, Dialect dialect) {
            try {
                return transactionCallback.execute(new JtaContext(ds, context));
            } catch (SQLException e) {
                throw dialect.convertException(e);
            }
        }

        @Override
        public <T> T withCurrentTransaction(TransactionCallback<T> transactionCallback, Dialect dialect) {
            try {
                return transactionCallback.execute(new JtaContext(ds, context));
            } catch (SQLException e) {
                throw dialect.convertException(e);
            }
        }

        @Override
        public boolean hasActiveTransaction() {
            try {
                return context.getUserTransaction().getStatus() == Status.STATUS_ACTIVE;
            } catch (SystemException e) {
                throw new RuntimeException(e);
            }
        }

        public static class JtaContext implements org.dalesbred.transaction.TransactionContext {
            private final DataSource ds;
            private final EJBContext context;

            public JtaContext(DataSource ds, EJBContext context) {
                this.ds = ds;
                this.context = context;
            }

            @Override
            public Connection getConnection() {
                try {
                    return ds.getConnection();
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }

            @Override
            public void setRollbackOnly() {
                context.setRollbackOnly();
            }

            @Override
            public boolean isRollbackOnly() {
                return context.getRollbackOnly();
            }
        }
    }
}
```

Not really production ready (mild understatement) but OK for my current POC...
