### ISSUE TITLE
`java.sql.Date` not converted to `java.time.LocalDate` for instantiation

### ISSUE THREAD

**Issue by alecharp** [EvidentSolutions/dalesbred#18]
Hello,

I have a model defined as following:

``` java
public final class Event {
  private String id;
  private String title;
  private java.time.LocalDate date;

  public Event(String title, java.time.LocalTime date) {
    this.id = java.util.UUID.randomUUID().toString();
    this.title = title;
    this.date = date;
  }
}
```

which is stored in PostgreSQL in a table defined as 

``` sql
CREATE TABLE events (
  id VARCHAR(50) PRIMARY KEY,
  title TEXT NOT NULL,
  date DATE
);
```

Storing an instance is not an issue. Pretty easy (thanks to you) but fetching the element is not that simple. I'm getting `org.dalesbred.internal.instantiation.InstantiationFailureException: could not find a way to instantiate class xx.Event with parameters [id: java.lang.String, title: java.lang.String, date: java.sql.Date] (query: SELECT * FROM events WHERE id = ? [xxx])
`

It won't bother me to have a `private` constructor that would accept the `id` as a parameter, but having the `java.sql.Date` should not appear. I didn't registrer a custom convertor but from [the web-site](http://dalesbred.org/docs/reference/#_custom_type_conversions), I was expecting the field to be converted to a `java.time.LocalDate`. 

Could you please tell me how to fix that? I'd be happy to contribute if this behavior is more a bug than a PEBCAK (which I suspect). Thanks

**Comment by alecharp** [comment]
just need to have a `public` constructor as

``` java
public Event(String id, String title, java.time.LocalTime date){}
```

and it's working. Just thinking of some enhancement: having such constructor is not a big deal, if it could be `private` or `default`. Might be useful to have an annotation to declare the constructor as the one to use for db -> java conversion. 

Thanks anyway. Good project!

**Comment by komu** [comment]
Good that you found the solution. Perhaps I could improve the error message of the exception to include examples of common problems.

Dalesbred does not try to access any members that are inaccessible to it using the normal accessibility rules of Java. I know that it would be possible to make the private and package protected members accessible using reflection, but I consider that to be questionable style.

I think that code is supposed to communicate its intent clearly and to me marking a constructor `private` means that it's not accessed outside the class. I like to compare the situation to the case where you'd implement DAO manually using raw JDBC: you'd need to make the constructor public in order to call it from your DAO. Dalesbred just automates the grunt work, but otherwise abides by the same rules as your own code would.

That said, I'm not overly dogmatic about this: I might relax the rules to be more permissive in the future. However, that might lead into some unforeseen problems (e.g. picking up unexpected constructors) so I don't wish to make hasty decisions because once the rules have been relaxed, there's no way to tighten the rules without breaking backwards compatibility.

I have thought about adding an annotation to tell Dalesbred which constructor to use. If the annotation would be present, then the normal (quite complex) constructor selection logic would be skipped and the constructor with annotation would always be used. And like you propose, it would make sense to support even private constructors in that case: the annotation would make it clear that even though the constructor is private, it's used by Dalesbred. I added issue #19 about this and will probably implement it for 1.1.

Thanks!
