### ISSUE TITLE
Example of code to retrive 

### ISSUE THREAD

**Issue by fabriciofx** [EvidentSolutions/dalesbred#22]
Hi guys!

I'm studying dalesbed but unfortunately I have some doubts. For example, imagine these classes:

``` java

public final Phone {
   public enum State { ACTIVE, INACTIVE };
   private final String number;
   private final int country;
   private final State state;

   public Phone(State state, String number, int country) {
     this.state = state;
     this.number = number;
     this.country = country;
   }
   // only get methods (there are not set methods!)
}

public final class Person {
    private final String name;
    private List<Phone> phones;

    public Person(String name, List<Phone> phones) {
      this.name = name;
      this.phones = phones;
    }
   // only get methods (there are not set methods!)
}
```

So, I'm looking for an example how can I retrive all persons stored in my database.

Thanks in advance!

**Comment by komu** [comment]
Hi! Sorry for the delayed answer.

Dalesbred tries to keep the level of magic at minimum and just makes it easier to map your result sets to Java. In this case the problem is that the structure of the result set returned from database is completely different what you want in Java.

So you'd probably want to execute a query along the following lines:

``` sql
select person.name, phone.number, phone.state, phone.country
    from person
    left outer join phone on person.id = phone.person_id
    order by person.name
```

But then the problem is that you'll get one row for each phone instead of row per person. So I'd simply make a temporary class matching the structure of this result-set and then perform a loop over the results to create Persons with their Phones. I agree that it's a bit annoying, but it's simple and doesn't require any magic.

If you're using a database like PostgreSQL, an alternative would be to actually return a result set with the structure "name, phone[]" in which case you could map the results directly to your objects.
