### ISSUE TITLE
Alias names or any name column name get is in capital letters

### ISSUE THREAD

**Issue by gauravrmazra** [EvidentSolutions/dalesbred#27]
Hi,

Dalesbred capitalizes the column names ignoring alias name when Resultable is used. Even tried to used executeQuery by passing custom ResultSetProcessor. Even then it is capitalizing the  column names.

When I run same queries on vanilla JDBC it returns the column name either as in database or as asked in the alias name of query.

Is it a bug in dalesbred?

**Comment by komu** [comment]
Hi!

What database are you using? What JDBC-driver and version?

Dalesbred passes `ResultSet` returned by JDBC driver directly to `ResultSetProcessor` so I don't see how it could possibly capitalize anything when using your custom `ResultSetProcessor`.

In any case, there's no code for capitalizing the column names in Dalesbred: it will do case-insensitive comparisons between columns returned by database and properties defined in Java, but it will not change anything.

How do you query the column names in your own code? It's worth noting that Dalesbred uses [getColumnLabel](https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSetMetaData.html#getColumnLabel-int-) instead of [getColumnName](https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSetMetaData.html#getColumnName-int-) to retrieve column aliases from `ResultSet`s. Perhaps your JDBC-driver capitalizes one and not the other? (This still wouldn't explain how custom `ResultSetProcessor` would return different results from vanilla JDBC-calls, though.)

Finally note that many databases capitalize the returned aliases unless you explicitly specify not to. For example running the following code against HSQLDB:

``` java
db.executeQuery(rs -> {
    ResultSetMetaData metaData = rs.getMetaData();

    for (int i = 1; i <= metaData.getColumnCount(); i++)
        System.out.println(metaData.getColumnLabel(i));

    return null;
}, "select 1 as foo, 2 as \"Bar\" from (values (1))");
```

This will print:

```
FOO
Bar
```

Are you sure that your vanilla JDBC code and Dalesbred code are functionally equivalent? If you still think there's something wrong with Dalesbred, could you please provide a short snippet of code for me to test? Thanks!
