### ISSUE TITLE
Unable to perform insert using findUniqueInt

### ISSUE THREAD

**Issue by mmadson** [EvidentSolutions/dalesbred#28]
Throws exception:

java.sql.SQLException: Can not issue data manipulation statements with executeQuery()

Using Mariadb jdbc connector, to connect to mysql db.

findUniqueInt("INSERT INTO...") occurs after a update() call within a transaction block.

**Comment by mmadson** [comment]
ugly workaround is to:

```
db.updateAndProcessGeneratedKeys(rs -> {
if(rs.next()) {
 return rs.getLong(1);
} else {
  throw new RuntimeException("unable to generate id");
}
}, new ArrayList<>(), "INSERT INTO...");
```

**Comment by komu** [comment]
You don't show the full SQL-query, so it's hard for me to comment on that, but on PostgreSQL you can add `RETURNING ...` to insert or update, effectively turning it into a query as far as the driver is concerned. So you can say:

``` java
int id = db.findUniqueInt("insert into foo (...) values (...) returning id");
```

I have no idea if MySQL supports something similar. In any case, `findUniqueInt` just executes a query as far as it's concerned.

`updateAndProcessGeneratedKeys` is indeed a proper way to perform this if the database does support something like `RETURNING ...`. You'd probably want to extract the code for building the `ResultSetProcessor` so that it doesn't need to be specified inline. So you'd end up with something like:

``` java
db.updateAndProcessGeneratedKeys(Results.uniqueLong(), emptyList(), "insert into...");
```
