### ISSUE TITLE
New method updateUnique for Database

### ISSUE THREAD

**Issue by jukkasi** [EvidentSolutions/dalesbred#32]
It would be nice to have updateUnique method for database which checks that exactly one row is updated and otherwise throws error. Basic idea is to protect from nasty bugs which can mess up the data if query is not executed as expected.

I think this is pretty common use case  but most of the developers probably forget to check returned rows  since it is too easy to just write database.update(..).

database.updateUnique would also act as a reminder for developer if check should be made.

**Comment by komu** [comment]
Great idea!

It's a simple feature, so I'll try to implement it soon, but of course a pull request would be appreciated. :)

**Comment by jukkasi** [comment]
Thinking further I can come up with two more maybe not so common use cases and not sure how they would fit in, something like

updateUniqueOrNone - succeeds only if 0 or 1 row is updated
updateExactly(int affectedRows, ...) - succeeds only if exactly number of affectedRows is updated

or maybe

updateOneRow / updateExactlyOneRow
updateAtMostOneRow
updateRows

Naming is hard at least.

Again, if included in Database, these would act as a good reminder for developer of possible outcomes.

**Comment by komu** [comment]
I was thinking about those other cases as well, but figured that's its probably best to leave them out completely. Updates with expected result count of 1 are really common operations and there should be a convenience methods for that. Other cases seems to be a lot more marginal and I'm not convinced that `db.updateExactly(4, sql, params)` would be clearer `if (db.update(sql, params) != 4) throw ...`.

Improving API surface is hard for learning, auto-completation and maintenance. And what has once been added can't be removed without breaking compatibility, so I'd tread carefully here. If there are compelling use cases for the other methods, they can always be added later.

In retrospect, if I'd were to design `update`-method now, I'd consider returning an `UpdateResult` instead of `int`. Then the various assertions could be methods on `UpdateResult` and there would not be a need to create a family of `update`-methods. Perhaps for 2.0 in 10 years or so. :)

**Comment by komu** [comment]
I pushed an initial implementation, but didn't merge to master yet because I'm not yet decided whether to use a new `NonUniqueUpdateException` or to reuse existing `NonUniqueResultException`.

It probably doesn't matter much either way, though: it's not like you're going to catch these specific exceptions anyway since they probably signify a bug in the code rather than a recoverable error.
